apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    description: LAN duckdns
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: duckdns
    location: lan
  name: dns-trick
  selfLink: /apis/apps/v1/namespaces/lan/deployments/duckdns
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: duckdns
      location: lan
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: LAN duckdns
      creationTimestamp: null
      labels:
        k8s-app: duckdns
        location: lan
      name: duckdns
    spec:
      containers:
      - env:
        - name: TZ
          value: UTC
        - name: TOKEN
          value: <INSERT-TOKEN>
        - name: SUBDOMAINS
          value: <INSERT-DOMAINS>
        image: ghcr.io/linuxserver/duckdns
        imagePullPolicy: Always
        name: duckdns
        resources: {}
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: false
      nodeSelector:
        location: lan
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
